CREATE TABLE User{
userID INTEGER(11) NOt NULL PRIMARY ,
username VARCHAR(12) NOT NULL,
email VARCHAR(255) NOT NULL ,
password INTEGER(11) NOT NULL,
gender BIT NOT NULL ,
birthday DATE,
address VARCHAR (255)
mobile INTEGER(15)
}
CREATE TABLE Email{

}